#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CPCantalapiedra 2018

INTERVALS_FILE_FIELD_TARGET = 0
INTERVALS_FILE_FIELD_START = 1
INTERVALS_FILE_FIELD_END = 2
INTERVALS_FILE_FIELD_COUNT = 3

## END